### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed> error when using install()

### ISSUE THREAD

**Issue by odogancay-ku** [yeongbin-jo/python-chromedriver-autoinstaller#27]
Here is the full log, 

```
Traceback (most recent call last):
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1441, in connect
    super().connect()
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 945, in connect
    self.sock = self._create_connection(
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ofaru\Desktop\Uni\Index\mailer2.py", line 27, in <module>
    chromedriver_autoinstaller.install()
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\__init__.py", line 20, in install
    chromedriver_filepath = utils.download_chromedriver(path)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\utils.py", line 199, in download_chromedriver
    chromedriver_version = get_matched_chromedriver_version(chrome_version)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\utils.py", line 165, in get_matched_chromedriver_version
    doc = urllib.request.urlopen('https://chromedriver.storage.googleapis.com').read()
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\ofaru\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

I am running on windows 10. Code used to work last time I checked.

**Comment by yeongbin-jo** [comment]
First, make sure that the chromedriver.storage.googleapis.com domain is accessible from the environment the code is running in. It seems most likely a DNS setting issue.
