### ISSUE TITLE
Error when running installation

### ISSUE THREAD

**Issue by donno2048** [yeongbin-jo/python-chromedriver-autoinstaller#4]
when running:
```python
import chromedriver_autoinstaller
chromedriver_autoinstaller.install()
```
I get:
```batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Elisha\AppData\Local\Programs\Python\Python38\lib\site-packages\chromedriver_autoinstaller\__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "C:\Users\Elisha\AppData\Local\Programs\Python\Python38\lib\site-packages\chromedriver_autoinstaller\utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "C:\Users\Elisha\AppData\Local\Programs\Python\Python38\lib\site-packages\chromedriver_autoinstaller\utils.py", line 117, in get_chrome_version
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
IndexError: list index out of range
```

**Comment by donno2048** [comment]
It was because of missing linking to the Chrome app
