### ISSUE TITLE
fails to detect 32-bit Chrome on 64-bit Windows

### ISSUE THREAD

**Issue by teridon** [yeongbin-jo/python-chromedriver-autoinstaller#67]
When 32-bit Chrome is installed (Enterprise system, I don't get a choice) on a 64-bit system, chromedriver-autoinstaller fails to detect Chrome is installed.

```
Traceback (most recent call last):
  File "C:\Users\teridon\Documents\git\webet-login\webet-login.py", line 22, in <module>
    chromedriver_autoinstaller.install()
  File "C:\Users\teridon\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\__init__.py", line 21, in install
    chromedriver_filepath = utils.download_chromedriver(path, no_ssl)
  File "C:\Users\teridon\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\utils.py", line 263, in download_chromedriver
    chrome_version = get_chrome_version()
  File "C:\Users\teridon\AppData\Local\Programs\Python\Python39\lib\site-packages\chromedriver_autoinstaller\utils.py", line 170, in get_chrome_version
    dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Google\\Chrome\\Application'


C:\Users\teridon>dir /b "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
chrome.exe

```

**Comment by Chetan11-dev** [comment]
This solution works; it uses the [Botasaurus Web Scraping Framework](https://github.com/omkarcloud/botasaurus) to create Chrome.

## Installation

```bash
pip install botasaurus
```

## Example

```python
from botasaurus import *

driver = bt.create_driver()

driver.get("http://www.python.org")
driver.prompt()
driver.quit()
```

**Comment by shawnCaza** [comment]
@teridon Thanks for bringing this up. We've addressed this issue in the current release.
